### ISSUE TITLE
[Request] Make mod compatible with StS v2.0, please

### ISSUE THREAD

**Issue by BennyAlex** [twanvl/sts-shop-mod#6]

**Comment by twanvl** [comment]
The version that is on steam should already work with StS v2 (tested with version 01-27-2020). What kind of error are you getting?

**Comment by BennyAlex** [comment]
Hey, thanks for reply.

I couldnt sell relics until I noticed I must buy the carpet, lol. Maybe you can add this information in the mod discription.
