### ISSUE TITLE
How to modify this mod?

### ISSUE THREAD

**Issue by scteam1994** [twanvl/sts-shop-mod#7]
Thanks for your great mod. I want to change the price of the rug in shop but I fail to find where it is. Since I am not familiar with Java can you tell me how to regenerate the .jar package?

**Comment by twanvl** [comment]
The code can be compiled with maven (`mvn package`). Or via the Makefile (`make all`).

The price of the rug is specified in https://github.com/twanvl/sts-shop-mod/blob/master/src/main/java/shopmod/relics/MerchantsRug.java#L55

**Comment by scteam1994** [comment]
Thanks for your quick reply. It seems that I couldn't package it on Mac OS since macOS version STS has no .jar but only a full packaged .app. When I run mvn package it shows 

_"Failed to execute goal on project ShopMod: Could not resolve dependencies for project shopmod:ShopMod:jar:1.1.2: The following artifacts could not be resolved: com.megacrit.cardcrawl:slaythespire:jar:016, basemod:BaseMod:jar:1.6.5, modthespire:ModTheSpire:jar:2.4.0: Could not find artifact com.megacrit.cardcrawl:slaythespire:jar:016 at specified path /Users/destination/Downloads/sts-shop-mod-master/../_ModTheSpire/desktop-1.0.jar -> [Help 1]"_

when I run make all it shows
_"convert large/MerchantsRug.png -resize 128x128 MerchantsRug.png
make[1]: convert: No such file or directory
make[1]: *** [MerchantsRug.png] Error 1
make: *** [all] Error 2"_

I tried resize the picture by hand and remove the convert line it shows
_"make -C src/main/resources/img/relics
make[1]: *** No rule to make target `MerchantsRug.png', needed by `all'.  Stop.
make: *** [all] Error 2"_

I will try later using window when I come home.

**Comment by scteam1994** [comment]
I finally made it. It needs change the path in pom file.
